name       : cadence
version    : 0.9.1
release    : 2
source     :
    - https://github.com/falkTX/Cadence/archive/v0.9.1.tar.gz : e530787ded0d53a3004c7a8260114ddb970c2aea43875d62eccd599ac96e1fd1
homepage   : https://github.com/falkTX/Cadence
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Collection of tools useful for audio production
description: |
    Cadence is a set of tools useful for audio production. Please note that it will take control over the PulseAudio configuration on the system. You will need to delete the ~/.pulse folder and then log in and out to get back the default configuration.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(dbus-python)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - a2jmidid
    - jack-capture
    - python3-qt5
rundeps    :
    - a2jmidid
    - jack-capture
    - pulseaudio-module-jack
    - python3-dbus
    - python3-qt5
setup      : |
    %patch -p1 < $pkgfiles/Fix-build-with-Qt-5.15+.patch
build      : |
    %make
install    : |
    %make_install PREFIX=/usr

    # It is just an empty directory.
    rm -rf $installdir/usr/share/cadence/icons

    # Remove claudia as it depends on ladish and flowcanvas, both of which are dead.
    rm -rf $installdir/usr/bin/claudia* \
           $installdir/usr/share/applications/claudia* \
           $installdir/usr/share/cadence/{icons,src}/{,ui_}claudia* \
           $installdir/usr/share/icons/hicolor/{128x128,16x16,256x256,48x48,scalable}/apps/claudia*
